packages:
  - 'packages/*'
  - 'registry'
  - 'playground'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@sublay/core@7.0.3'
  - '@sublay/expo@7.0.3'
  - '@sublay/react-js@7.0.3'
  - '@sublay/react-native@7.0.3'
  - '@sublay/ui-core-react-js@7.0.0'
  - '@sublay/ui-core-react-native@7.0.0'
